---
title: "Housekeeping"
author: "BIOF2014"
format: beamer
---

## Schedule

Tuesdays & Thursdays 4:00 pm - 5:50 pm

Locations: MW325 (3/F Meng Wah Complex) or CPD-3.29 (3/F Jockey Club Tower)


## Text books

Statistical Inference. George Casella, Roger L. Berger. 2002.

Statistical Inference for Everyone. Brian Blais. 2014.
https://open.umn.edu/opentextbooks/formats/619


## Assessments

| type            | weight | derivation | calculation | programming |
|-----------------|--------|------------|-------------|-------------|
| 20 quizzes      |  10%   |     Y      |      Y      |      N      |
| 2 assignments   |  15%   |     Y      |      Y      |      N      |
| 1 mid-term test |  20%   |     Y      |      Y      |      N      |
| 1 project       |  25%   |     N      |      N      |      Y      |
| 1 final exam    |  30%   |     Y      |      Y      |      N      |

Quizzes are your opportunity to practice for the mid-term test and final exam.

No calculator, computer, phone, or other electronic devices are allowed 
in the exam.

Plagiarism will *not* be tolerated.


## ChatGPT

As per university policy, instructors should make assessments
'ChatGPT-proof'.

ChatGPT is excellent at writing meaningless fluff, and it is mediocre at logic.
It is often overfitted to the questions in the training set.

ChatGPT can be useful for correcting grammar, improving writing, and perhaps
as a second opinion.

ChatGPT does poorly (0-50%) on most statistical questions.

ChatGPT answers are often vague. Their derivations seem helpful on the surface
but lack mathematical rigor and contain hallucinated/magical steps.


## Marking scheme

### Derivation and calculation questions

| Process                     | Result    |  Mark  |
|-----------------------------|-----------|--------|
| Correct                     | Correct   | 100%   |
| Correct but incomplete      | Null      | 10-90% |
| Mostly correct with errors  | Correct   | 40-80% |
| Mostly correct with errors  | Incorrect | 20-60% |
| Incorrect                   | Correct   | 0-20%  |
| Incorrect                   | Incorrect | 0%     |


## Marking scheme

### Proof questions

| Process                                   | Result |  Mark  |
|-------------------------------------------|--------|--------|
| Correct and well-justified                | Given  | 100%   |
| Correct and well-justified but incomplete | Given  | 10-90% |
| Correct without sufficient justification  | Given  | 10-60% |
| Correct with wrong justification          | Given  | 0-30%  |
| Incorrect                                 | Given  | 0%     |


## Marking scheme

### Programming project

| Criterion                                 | Weight |
|-------------------------------------------|--------|
| Code novelty\*                            | 20%    |
| Commit pattern                            | 20%    |
| Model performance, training               | 20%    |
| Model performance, test                   | 40%    |

\* >90\% similarity with another submission results in a grade of zero
for the entire project.


## Late submissions

The penalty for late submission is 10% per day.

Quizzes or assignments will *not* be graded after any answer is discussed or
released.


## Mathematical notations

We will use the mathematical notation introduced in Roger & Berger (2002)
throughout the course.

Learning and using the correct mathematical notation are critical!

Notations are invented to make expressions less ambiguous and more concise!

In the bioinformatics field, method descriptions are atrocious because few 
people learned the proper notations, which make communications very difficult.

