---
title: "Statistical Notations"
author: "BIOF2014"
format: pdf
pdf-engine: pdflatex
---

We will adopt the mathematical notation used in the following textbook.

> Statistical Inference. George Casella, Roger L. Berger. 2002.


## Common functions

| notation          | interpretation                                         |
|-------------------|--------------------------------------------------------|
| $\exp(x)$         | exponential function                                   |
| $\log(x)$         | natural logarithm function                             |
| ${N \choose k}$   | binomial coefficient ($N$ choose $k$)                  |
| $B(a, b)$         | beta function                                          |
| $\Gamma(a)$       | gamma function                                         |
| $\Gamma_K(a)$     | multivariate gamma function                            |


## Set theory

| notation          | interpretation                                         |
|-------------------|--------------------------------------------------------|
| $A = \{x, y, z\}$ | an event; a set of outcomes $x$, $y$, and $z$          |
| $\{x : \text{condition}\}$ | a set containing all $x$ that satisfies the condition |
| $\emptyset$       | empty set                                              |
| $x \in A$         | element $x$ is in set $A$                              |
| $A \subset B$     | set $A$ is contained in set $B$, possibly $A = B$      |
| $A \cap B$        | intersection of set $A$ and set $B$                    |
| $A \cup B$        | union of set $A$ and $B$                               |
| $A^c$             | complement of set A                                    |


## Linear algebra

| notation          | interpretation                                         |
|-------------------|--------------------------------------------------------|
| $\mathbf{x}$  | a column vector                                            |
| $\mathbf{x}^{\top} \mathbf{y}$ | dot product                               |
| $\mathbf{x} \mathbf{y}^{\top}$ | outer product                             |
| $\mathbf{X}$  | a matrix                                                   |
| $\mathbf{X}^{\top}$ | transpose of $\mathbf{X}$                            |
| $\mathbf{X}^{-1}$ | inverse of $\mathbf{X}$                                |
| $|\mathbf{X}|$| determinant of $\mathbf{X}$                                |
| $\text{tr}(\mathbf{X})$| trace of $\mathbf{X}$                             |
| $\mathbf{X} \mathbf{Y}$| matrix product                                    |
| $\mathbf{X} \odot \mathbf{Y}$| element-wise product                        |
| $\mathbf{X} \otimes \mathbf{Y}$| Kronecker product                         |


## Probability theory

| notation          | interpretation                                         |
|-------------------|--------------------------------------------------------|
| $P(A)$            | probability that event $A$ occurs under the probability function $P$ |
| $P(A, B)$         | joint probability that both events $A$ and $B$ occur   |
| $P(A \mid B)$     | conditional probability that event $A$ occurs given that $B$ occurred  |
| $X \in \mathcal{X}$  | random variable $X$ with domain $\mathcal{X}$       |
| $P_X(X = x)$      | probability that random variable $X$ takes on a realized value $x$; often abbreviated as $P(X = x)$ or $P(x)$ |
| $F_X(x \mid \theta)$ | cumulative distribution function (cdf) of random variable $X$ with parameter $\theta$ |
| $f_X(x \mid \theta)$ | probability density function (pdf) if $X$ is continuous; probability mass function (pmf) if $X$ is discrete |
| $f(x, y)$         | joint pdf/pmf on random variable $X$ and $Y$           |
| $f(x \mid y)$     | conditional pdf/pmf of $X$ given $Y$                   |
| $\text{E}[ X ]$   | expectation of random variable X under $f_X(x)$        |
| $\text{Var}[ X ]$ | variance of X under $f_X(x)$                           |
| $X \sim f(\theta)$ | $X$ is distributed according to $f_X(x \mid \theta)$  |
| $X \sim F(\theta)$ | same as above                                         |
| $X \sim Y$        | random variable $X$ follows the distribution of $Y$    |
| $X \sim \text{Bernoulli}(\theta)$ | $X$ is distributed according to a Bernoulli distribution with parameter $\theta$, and similarly for other distributions |

Uppercase English letters $X, Y, Z, \ldots$ denote random variables
with realized values $x, y, z, \ldots$, with the latter written in lowercase letters.

Letters $i$, $j$, $k, \ldots$ are often used to denote indices with upperbounds
$N, J, K, \ldots$.

Greek letters, such as
$\alpha, \beta, \gamma, \eta, \theta, \lambda, \mu, \rho, \sigma,
\tau, \phi, \ldots$
are often used to denote parameters.

Bolded letters $\mathbf{x}$ and $\mathbf{X}$ denote vectors and matrices.


## Bayesian short-hands

| notation          | interpretation                                         |
|-------------------|--------------------------------------------------------|
| $p(x)$            | $f_X(X = x)$; pdf or pmf                               |
| $p(x, y)$         | $f_{X, Y}(X = x, Y = y)$; joint pdf or pmf              | 
| $p(x \mid y)$     | $f_{X \mid Y}(X = x \mid Y = y)$; conditional pdf or pmf |


## Operators

The intersection and union of sets $A_1, A_2, \ldots, A_N$ are
$$
\bigcap_i^N A_i \quad \text{and} \quad \bigcup_i^N A_i .
$$

Operators such as $\sum$ (sum), $\prod$ (product), $\int$ (integration), etc.
can take a set that the index enumerates over. For example, the sum and
product of $x_i$ over all index value $i$ in set $A$ are
$$
\sum_{i \in A} x_i \quad \text{and} \quad \prod_{i \in A} x_i .
$$

Similarly, to integrate over all value $\theta$ in set $\Theta$,
we write
$$
\int_{\Theta} f(\theta) \, d \theta .
$$

