---
title: "Teaching, Learning, Education, and Entertainment"
author: "BIOF2014"
format: pdf
---

## The case of Maitland Jones Jr.

Read the following articles.

[New York University professor fired after students say his class was too hard][1]

[Alumni respond to Professor Emeritus Maitland Jones Jr.’s termination from NYU][2]

[Wikipedia article on Maitland Jones Jr.][3]

[1]: https://www.theguardian.com/us-news/2022/oct/06/nyu-professor-fired-maitland-jones-jr-student-petition
[2]: https://www.dailyprincetonian.com/article/2022/10/maitland-jones-nyu-princeton-professor-terminated
[3]: https://en.wikipedia.org/wiki/Maitland_Jones_Jr.


## Questions

The student's petition to New York University reads: 

"We urge you to realize that a class with such a high percentage of withdrawals 
and low grades has failed to make students’ learning and wellbeing a priority 
and reflects poorly on the chemistry department as well as the institution as 
a whole."

1. Given his track record, was Dr. Jones more or less likely to be an effective 
teacher?

2. Do low student grades in a course indicate that the teacher of the course is 
ineffective?

3. Over the past two years, Dr. Jones noticed a drastic decline in the grades of
the students who took his course, even though the exams have not changed in 
terms of difficulty. More students skipped lectures, and the number of misread 
questions on tests had increased. Should he make the exams easier?

4. Should the exam in this course to be easier than the 
equivalent course from the statistics department (i.e. STAT2601)?

5. In the era of ChatGPT, should assignments be designed so that ChatGPT can
score perfect on them?

\pagebreak


Andrej Karpathy, a founding member of OpenAI, posted on X (formerly Twitter):

\# on shortification of "learning"

There are a lot of videos on YouTube/TikTok etc. that give the appearance of education, but if you look closely they are really just entertainment. This is very convenient for everyone involved : the people watching enjoy thinking they are learning (but actually they are just having fun). The people creating this content also enjoy it because fun has a much larger audience, fame and revenue. But as far as learning goes, this is a trap. This content is an epsilon away from watching the Bachelorette. It's like snacking on those "Garden Veggie Straws", which feel like you're eating healthy vegetables until you look at the ingredients.

Learning is not supposed to be fun. It doesn't have to be actively not fun either, but the primary feeling should be that of effort. It should look a lot less like that "10 minute full body" workout from your local digital media creator and a lot more like a serious session at the gym. You want the mental equivalent of sweating. It's not that the quickie doesn't do anything, it's just that it is wildly suboptimal if you actually care to learn.

I find it helpful to explicitly declare your intent up front as a sharp, binary variable in your mind. If you are consuming content: are you trying to be entertained or are you trying to learn? And if you are creating content: are you trying to entertain or are you trying to teach? You'll go down a different path in each case. Attempts to seek the stuff in between actually clamp to zero.

So for those who actually want to learn. Unless you are trying to learn something narrow and specific, close those tabs with quick blog posts. Close those tabs of "Learn XYZ in 10 minutes". Consider the opportunity cost of snacking and seek the meal - the textbooks, docs, papers, manuals, longform. Allocate a 4 hour window. Don't just read, take notes, re-read, re-phrase, process, manipulate, learn.

And for those actually trying to educate, please consider writing/recording longform, designed for someone to get "sweaty", especially in today's era of quantity over quality. Give someone a real workout. This is what I aspire to in my own educational work too. My audience will decrease. The ones that remain might not even like it. But at least we'll learn something.

## Questions

1. What is the difference between entertainment and education?

2. How do you know whether you have learned something?

- You obtained good exam grade.
- You feel that you are struggling to understand, and you eventually 
  overcome this feeling.
- A year from you learned the topic, you recalled a concept and applied it to 
  a new problem.

3. Is learning supposed to be fun?
