---
title: "Quiz 4"
author: "BIOF2014"
format: pdf
---

## Question 1

Consider the proof below.

Assume
$$
(x + y)^{N-1} = \sum_{i=0}^{N-1} \binom{N-1}{i} x^i y^{N - 1 - i} .
$$

Then,
$$
\begin{aligned}
(x + y)^N &= (x + y) (x + y)^{N-1} \\
 &= (x + y) \sum_{i=0}^{N-1} \binom{N-1}{i} x^i y^{N - 1 - i} \\
 &= \left( \sum_{i=0}^{N-1} \binom{N-1}{i} x^{i+1} y^{N - 1 - i} \right)
  + \left( \sum_{i=0}^{N-1} \binom{N-1}{i} x^i y^{N - i} \right) .
\end{aligned}
$$

In the first sum, re-index with \(j = i + 1\). In the second sum, substitute \(j = i\).
This gives
$$
(x + y)^N =
    \left( \sum_{j=1}^{N} \binom{N-1}{j-1} x^j y^{N - j} \right)
  + \left( \sum_{j=0}^{N-1} \binom{N-1}{j} x^j y^{N - j} \right) .
$$

Combining the two sums gives
$$
(x + y)^N =
  \left( \sum_{j=0}^{N} \left( \binom{N-1}{j-1} +  \binom{N-1}{j} \right) 
     x^j y^{N - j} \right) .
$$

By the binomial coefficient identity,
$$
\begin{aligned}
(x + y)^N &= \sum_{j=0}^{N} \binom{N}{j} x^j y^{N-j} .
\end{aligned}
$$

Therefore, by induction,
$$
(x + y)^N = \sum_{j=0}^{N} \binom{N}{j} x^j y^{N-j},
 \quad N \in \{0, 1, \ldots\}. \quad \blacksquare
$$


Which step of the proof above is not well justified or contains an error?


Remark: On the exam, you will be required to provide fully justified proofs, instead of spotting errors in proofs.


## Question 2

In the Card Drawing tutorial, suppose you draw another set of 8 cards before putting the cards from the first round back into the deck. 

Derive the pmf for the number of non-face
cards that would be in this second sample of cards.

Define the variables as follows:

\( N \), number of cards in the deck

\( K \), number of non-face cards in the deck

\( n_i \), number of cards drawn in the \(i\)th round

\( k_i \), number of non-face cards drawn in the \(i\)th round


