---
title: "Neuronal Spike Trains"
author: "BIOF2014"
format:
  pdf:
    include-in-header:
      - text: |
          \usepackage{amsfonts}
          \usepackage{amsmath}
          \usepackage{amssymb}
          \usepackage{amsthm}
          \usepackage{fixmath}
          \usepackage[english]{babel}
          \usepackage{mathrsfs}
          \usepackage{mathtools}
---

## Problem

You are measuring spike trains from a neuron, and you measured
the number of spikes observed in multiple experiments, each with
different recording time intervals.

You recorded the following results:

| time interval (min) | number of spikes        |
|:-------------------:|:-----------------------:|
|         1           |            6            |
|         1           |            8            |
|         1           |            2            |
|         2           |           11            |
|         2           |           14            |
|         3           |           14            |
|         3           |           17            |

You performed the experiment again after treating the neuron with
a compound.

| time interval (min) | number of spikes        |
|:-------------------:|:-----------------------:|
|         1           |            1            |
|         2           |            3            |
|         4           |            6            |
|         5           |            9            |


What is the spiking rate per minute
before and after compound treatment?


## Tasks

1. Design statistical model to fit the data from a neuronal
   spike train experiment.

2. Implement the statistical model in [Stan][1] to estimate
   the posterior distribution of the spiking rates in
   under different treatment conditions.

3. Derive the posterior distribution of the spiking rates.
   
4. What effect does the compound have on spiking rate?


[1]: https://mc-stan.org/
