---
title: "Beta-binomial and Dirichlet-multinomial models"
author: "David J. H. Shih"
format:
  beamer:
    include-in-header:
      - text: |
          \usepackage{amsfonts}
          \usepackage{amsmath}
          \usepackage{amssymb}
          \usepackage{amsthm}
          \usepackage{bm}
          \usepackage{bbm}
          \usepackage[english]{babel}
          \usepackage{fixmath}
          \usepackage{mathrsfs}
          \usepackage{mathtools}
classoption: t  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center");
```

## Intended learning outcomes {.c}

- Recognize and apply the beta-binomial model
- Recognize and apply the Dirichlet-multinomial model


## Solving for the posterior

Given observation $X$ and parameter $\theta$,
solve for $p\left(\theta \mid x\right)$.
$$
\begin{aligned}
p\left(x \mid \theta\right) \, p\left(\theta\right) 
&= h(x) \, g(x, \theta) . \\
p\left(x\right)
&= \int_{\mathcal{\Theta}}
    p\left(x \mid \theta\right) \, p\left(\theta\right) \, 
   d\theta 
 = h(x) \int_{\mathcal{\Theta}} \, g(x, \theta) \, d\theta .
\end{aligned}
$$

Therefore, the posterior is
$$
\begin{aligned}
p\left(\theta \mid x\right)
&= \frac{ p\left(x \mid \theta\right) \, p\left(\theta\right) }
        { p\left(x\right) } 
 = \frac{ h(x) \, g(x, \theta) }
        { h(x) \int_{\mathcal{\Theta}} g(x, \theta) \, d\theta } \\
&= \frac{ g(x, \theta) }
        { \int_{\mathcal{\Theta}} g(x, \theta) \, d\theta } \\
&= c(x)^{-1} g(x, \theta) ,
\end{aligned}
$$
where $c(x) = \int_{\mathcal{\Theta}} g(x, \theta) \, d\theta$.


## Solving for the posterior, simplified

Given observation $X$ and parameter $\theta$,
solve for $p\left(\theta \mid x\right)$.

The posterior is
$$
\begin{aligned}
p\left(\theta \mid x\right)
&\propto p\left(x \mid \theta\right) \, p\left(\theta\right) \\
&= h(x) \, g(x, \theta) \\
&\propto g(x, \theta)
\end{aligned}
$$

Therefore,
$$
\begin{aligned}
p\left(\theta \mid x\right)
&= c(x)^{-1} g(x, \theta) ,
\end{aligned}
$$
where $c(x) = \int_{\mathcal{\Theta}} g(x, \theta) \, d\theta$.

\bigskip

If $p\left(\theta\right)$ is a **conjugate prior**, then
$c(x)$ can be solved easily.


## Conjugate prior

If $p\left(\theta\right)$ is conjugate to $p\left(x \mid \theta\right)$,
then $p\left(\theta \mid x\right)$ will be in the same probability
distribution family.

In this case, we call $p\left(\theta\right)$ a **conjugate prior**.
For example,

| $p\left(\theta\right)$ | $p\left(x \mid \theta\right)$ |
|--------------|--------------------|
| beta         |  Bernoulli         |
| beta         |  binomial          |
| Dirichlet    |  categorical       |
| Dirichlet    |  multinomial       |
| gamma        |  Poisson           |
| normal-gamma |  univariate normal |


## Beta-binomial model

$$
X \sim \text{Binomial}\left( N, \theta \right), \quad
\theta \sim \text{Beta}\left(a, b\right)
$$
$$
\text{Binomial}\left( x \mid N, \theta \right) =
\binom{N}{x} \theta^x \, (1 - \theta)^{N - x}
$$
$$
\text{Beta}\left(x \mid \alpha, \beta\right) =
 B(\alpha, \beta)^{-1} x^{\alpha - 1} (1 - x)^{\beta - 1}
$$


---

\


## Dirichlet-multinomial model

$$
\symbfit{X} \sim \text{Multinomial}\left( N, \symbfit{\theta} \right), \quad
\symbfit{\theta} \sim \text{Dirichlet}\left( \symbfit{d} \right)
$$
$$
\text{Multinomial} \left(\symbfit{x} \mid N, \symbfit{\theta} \right)
= \frac{\Gamma(N + 1)}{\prod_k \Gamma(x_k + 1)} \prod_k \theta_k^{x_k}
$$
$$
\text{Dirichlet}\left(\symbfit{x} \mid \symbfit{\alpha} \right) 
= \frac{1}{B\left(\symbfit{\alpha}\right)} \prod_k^K x_k^{\alpha_k - 1}
$$

---

\


## Summary

Conjugate priors facilitate fast Bayesian updates.

\bigskip

### Intended learning outcomes {.c}

- Recognize and apply the beta-binomial model
- Recognize and apply the Dirichlet-multinomial model
