---
title: "Baccarat chemin de fer"
author: "BIOF2014"
format:
  pdf:
    include-in-header:
      - text: |
          \usepackage{amsfonts}
          \usepackage{amsmath}
          \usepackage{amssymb}
          \usepackage{amsthm}
          \usepackage{bm}
          \usepackage{bbm}
          \usepackage[english]{babel}
          \usepackage{fixmath}
          \usepackage{mathrsfs}
          \usepackage{mathtools}
---

We will play the *chemin de fer* variant of the Baccart card game.

## Game rules

We will use *one* deck of cards.

One person will be the **Banker**. One person will be the **Player**.

The Banker will deal the cards. 
The Player will record the outcomes.

You will play **10** rounds of the game, while recording the cards and the winner.
**You will use the results generated by all groups**.


### Hand value

The objective of the game is to maximize the value of a hand, which consists
initially of two cards, and a third card may be dealth, depending on the
outcome.

- Cards Ace to Nine are worth 1 to 9 respectively.
- Ten and face cards are worth 0.
- The value of a hand is equal to the sum of the values of the cards, modulo
  10. In other words, only the last digit of the sum is kept.

### Setup

1. The Banker shuffles the deck.
2. The Player cuts the deck.

### One round of the game

1. Deal one card face **up** to the Player and then to the Banker.
2. Deal a second card face **up** to the Player and the Banker.
3. If either Player or Banker has a hand value of 8 or 9 (called **natural**), 
   compare the hands and declare the winner or a tie.
4. If the Player wishes to **hit**, deal a third card face up to the Player.
   Otherwise, the Player **stands** (i.e. hand remains the same).
5. If the Banker wishes to hit, deal a third card face up to the Banker.
   Otherwise, the Banker stands.
6. Compare the hands and declare the winner or a tie.
7. Remove all cards from play to start the next round.


## Questions

1. Traditionally, in *chemin de fer*, the first two cards for each hand
   are dealt face down. Explain whether this makes a difference
   to the outcomes of the game.
2. Typically, in *chemin de fer*, six decks or more are mixed together. 
   Explain whether this makes a difference.
3. What are the empirical marginal probabilities of obtaining a final
   hand value of 9 for the Player and the Banker?
4. Derive the theoreotical marginal probability of obtaining a final
   hand value of 9 for the Player and the Banker.
   Assume that an infinite number of decks are shuffled together.
5. Derive the theoreotical conditional probabilty distribution of
   the hand value with a third card if the first two cards have a value
   of 7. Assume that an infinite number of decks are shuffled together.


## Bonus question

1. Assume that the first two cards for each hand are dealt face down.
   Prove whether the following strategy is optimal for the Player:
   - Hit on hand values of 5 and below;
   - Stand otherwise.

